### ISSUE TITLE
ManagerCollection Usage

### ISSUE THREAD

**Issue by ablond** [B0ulzy/boulzy-manager-bundle#7]
I just saw that the ManagerCollection was deleted in the V3.

I use it in the current stable version with ApiPlatform. It's really interesting when this feature is paired with the Data-Persisters of ApiPlatform : https://api-platform.com/docs/core/data-persisters

Here's a quick example : 
```
namespace App\DataPersister;

use ApiPlatform\Core\DataPersister\DataPersisterInterface;
use Boulzy\ManagerBundle\Collection\ManagerCollection;

class ManagerDataPersister implements DataPersisterInterface
{
    /** @var ManagerCollection */
    private $managerCollection;

    /**
     * ManagerDataPersister constructor.
     * @param ManagerCollection $managerCollection
     */
    public function __construct(ManagerCollection $managerCollection)
    {
        $this->managerCollection = $managerCollection;
    }

    /**
     * @inheritdoc
     */
    public function supports($data): bool
    {
        return $this->managerCollection->exists($data);
    }

    /**
     * @inheritdoc
     */
    public function persist($data)
    {
        $manager = $this->managerCollection->get($data);

        if (!$this->isDataExist($data)) {
            $manager->create($data);
        } else {
            $manager->update($data);
        }

        return $data;
    }

    /**
     * @inheritdoc
     */
    public function remove($data)
    {
        $manager = $this->managerCollection->get($data);
        $manager->delete($data);
    }

    /**
     * Determine if data exist or not in our storage
     * TODO :: Refactor this ugly hack !
     *
     * @return bool
     */
    private function isDataExist($data) :bool
    {
        try {
            $data->getId();
        } catch (\Error $e) {
            return false;
        }

        return true;
    }
```

With this, if a Manager exist for a given Object, ApiPlatform will use it dynamically.

**Comment by B0ulzy** [comment]
I find the implementation of the ManagerCollection a little messy and could not think of a concrete use case, that's why I thought of removing it in the v3. Now that a concrete case has been found, I will keep the concept, but it could be with a different, cleaner implementation though!

**Comment by B0ulzy** [comment]
@ablond The v3 version of the bundle is available in beta. It would be a pleasure to have your opinion if you have the time to check. I still have to improve documentation.

The `ManagerCollection` role is a little different and is now a `ManagerBag`, it doesn't have any logic.

A `ManagerFactory` is available to retrieve a manager by its supported class, or to generate one if none exist, so I think its the service that better fits your needs!
